name: Publish Package to npmjs

on:
    push:
        branches: main

jobs:
    check_commit_message:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check for "[skip_publish]" in the commit message
              id: check_message
              run: |
                  echo "COMMIT_MSG=$(git log -1 --pretty=format:'%s')" >> $GITHUB_OUTPUT
                  if [[ "$COMMIT_MSG" == *"[skip_publish]"* ]]; then
                      echo "skip_publish=true" >> $GITHUB_OUTPUT
                  else
                      echo "skip_publish=false" >> $GITHUB_OUTPUT
                  fi
    publish:
        runs-on: ubuntu-latest
        needs: check_commit_message
        if: needs.check_commit_message.outputs.skip_publish == 'false'
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  registry-url: "https://registry.npmjs.org"
            - run: npm ci
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
